### ISSUE TITLE
Rust build issues in projects outside `examples` directory

### ISSUE THREAD

**Issue by kcsmnt0** [agg23/openfpga-litex#8]
I'm able to build the Rust example programs in this repository, but I haven't managed to build any projects *outside* the repository's `examples` directory. This is my first time interacting with a `no_std` codebase, so I'm probably missing something about how the build process is supposed to work, but I've searched around quite a bit and haven't been able to make much progress on it.

Here's what I did:

1. Create a Git project in a folder named `test` with a subfolder named `vendor`.
2. Add `openfpga-litex` into `test/vendor` as a Git submodule.
3. Recursively copy everything from `test/vendor/openfpga-litex/lang/rust/examples/minimal` into `test`.
4. Update `test/build.rs` so that `dest_path` points to `vendor/openfpga-litex/lang/linker`.
5. Update `test/Cargo.toml` so that the path for `litex-openfpga` is `vendor/openfpga-litex/lang/rust/crates/litex-openfpga`.
6. Run `cargo build --release` from `test` as the working directory.

Here's the error I get:

```
error: language item required, but not found: `eh_personality`
  |
  = note: this can occur when a binary crate with `#![no_std]` is compiled for a target where `eh_personality` is defined in the standard library
  = help: you may be able to compile for a target that doesn't need `eh_personality`, specify a target with `--target` or in `.cargo/config`

error: could not compile `minimal` (bin "minimal") due to 1 previous error
```

If I switch to `test/vendor/openfpga-litex/lang/rust/examples/minimal` as the working directory, `cargo build --release` builds without issue. I expected the build to work the same way with the directory structure just transposed like this, but I assume I might have broken some invariant by rearranging things?

I tried `cargo build --release --target riscv32imafc-unknown-none-elf`, which gets me farther, but then the linker fails with several `undefined symbol` errors:
```
  = note: rust-lld: error: undefined symbol: _mp_hook
          >>> referenced by riscv_rt.218362806a8ccdf2-cgu.0
          >>>               riscv_rt-3c2b5aa454c093c8.riscv_rt.218362806a8ccdf2-cgu.0.rcgu.o:(_start_rust) in archive /home/kcsmnt0/src/test/target/riscv32imafc-unknown-none-elf/release/deps/libriscv_rt-3c2b5aa454c093c8.rlib
          
          rust-lld: error: undefined symbol: __pre_init
          >>> referenced by riscv_rt.218362806a8ccdf2-cgu.0
          >>>               riscv_rt-3c2b5aa454c093c8.riscv_rt.218362806a8ccdf2-cgu.0.rcgu.o:(_start_rust) in archive /home/kcsmnt0/src/test/target/riscv32imafc-unknown-none-elf/release/deps/libriscv_rt-3c2b5aa454c093c8.rlib
          
          rust-lld: error: undefined symbol: _ebss
          >>> referenced by riscv_rt.218362806a8ccdf2-cgu.0
          >>>               riscv_rt-3c2b5aa454c093c8.riscv_rt.218362806a8ccdf2-cgu.0.rcgu.o:(_start_rust) in archive /home/kcsmnt0/src/test/target/riscv32imafc-unknown-none-elf/release/deps/libriscv_rt-3c2b5aa454c093c8.rlib
          >>> referenced by riscv_rt.218362806a8ccdf2-cgu.0
          >>>               riscv_rt-3c2b5aa454c093c8.riscv_rt.218362806a8ccdf2-cgu.0.rcgu.o:(_start_rust) in archive /home/kcsmnt0/src/test/target/riscv32imafc-unknown-none-elf/release/deps/libriscv_rt-3c2b5aa454c093c8.rlib
          
          rust-lld: error: undefined symbol: _sbss
          >>> referenced by riscv_rt.218362806a8ccdf2-cgu.0
          >>>               riscv_rt-3c2b5aa454c093c8.riscv_rt.218362806a8ccdf2-cgu.0.rcgu.o:(_start_rust) in archive /home/kcsmnt0/src/test/target/riscv32imafc-unknown-none-elf/release/deps/libriscv_rt-3c2b5aa454c093c8.rlib
          >>> referenced by riscv_rt.218362806a8ccdf2-cgu.0
          >>>               riscv_rt-3c2b5aa454c093c8.riscv_rt.218362806a8ccdf2-cgu.0.rcgu.o:(_start_rust) in archive /home/kcsmnt0/src/test/target/riscv32imafc-unknown-none-elf/release/deps/libriscv_rt-3c2b5aa454c093c8.rlib
          
          rust-lld: error: undefined symbol: _sdata
          >>> referenced by riscv_rt.218362806a8ccdf2-cgu.0
          >>>               riscv_rt-3c2b5aa454c093c8.riscv_rt.218362806a8ccdf2-cgu.0.rcgu.o:(_start_rust) in archive /home/kcsmnt0/src/test/target/riscv32imafc-unknown-none-elf/release/deps/libriscv_rt-3c2b5aa454c093c8.rlib
          >>> referenced by riscv_rt.218362806a8ccdf2-cgu.0
          >>>               riscv_rt-3c2b5aa454c093c8.riscv_rt.218362806a8ccdf2-cgu.0.rcgu.o:(_start_rust) in archive /home/kcsmnt0/src/test/target/riscv32imafc-unknown-none-elf/release/deps/libriscv_rt-3c2b5aa454c093c8.rlib
          
          rust-lld: error: undefined symbol: _sidata
          >>> referenced by riscv_rt.218362806a8ccdf2-cgu.0
          >>>               riscv_rt-3c2b5aa454c093c8.riscv_rt.218362806a8ccdf2-cgu.0.rcgu.o:(_start_rust) in archive /home/kcsmnt0/src/test/target/riscv32imafc-unknown-none-elf/release/deps/libriscv_rt-3c2b5aa454c093c8.rlib
          >>> referenced by riscv_rt.218362806a8ccdf2-cgu.0
          >>>               riscv_rt-3c2b5aa454c093c8.riscv_rt.218362806a8ccdf2-cgu.0.rcgu.o:(_start_rust) in archive /home/kcsmnt0/src/test/target/riscv32imafc-unknown-none-elf/release/deps/libriscv_rt-3c2b5aa454c093c8.rlib
          
          rust-lld: error: undefined symbol: _setup_interrupts
          >>> referenced by riscv_rt.218362806a8ccdf2-cgu.0
          >>>               riscv_rt-3c2b5aa454c093c8.riscv_rt.218362806a8ccdf2-cgu.0.rcgu.o:(_start_rust) in archive /home/kcsmnt0/src/test/target/riscv32imafc-unknown-none-elf/release/deps/libriscv_rt-3c2b5aa454c093c8.rlib
          
          rust-lld: error: undefined symbol: _max_hart_id
          >>> referenced by asm.S:60
          >>>               riscv-rt.o:(.init+0x54) in archive /home/kcsmnt0/src/test/target/riscv32imafc-unknown-none-elf/release/deps/libriscv_rt-3c2b5aa454c093c8.rlib
          >>> referenced by asm.S:61
          >>>               riscv-rt.o:(.init+0x58) in archive /home/kcsmnt0/src/test/target/riscv32imafc-unknown-none-elf/release/deps/libriscv_rt-3c2b5aa454c093c8.rlib
          
          rust-lld: error: undefined symbol: _stack_start
          >>> referenced by asm.S:61
          >>>               riscv-rt.o:(.init+0x64) in archive /home/kcsmnt0/src/test/target/riscv32imafc-unknown-none-elf/release/deps/libriscv_rt-3c2b5aa454c093c8.rlib
          
          rust-lld: error: undefined symbol: _hart_stack_size
          >>> referenced by asm.S:61
          >>>               riscv-rt.o:(.init+0x6C) in archive /home/kcsmnt0/src/test/target/riscv32imafc-unknown-none-elf/release/deps/libriscv_rt-3c2b5aa454c093c8.rlib
          >>> referenced by asm.S:62
          >>>               riscv-rt.o:(.init+0x70) in archive /home/kcsmnt0/src/test/target/riscv32imafc-unknown-none-elf/release/deps/libriscv_rt-3c2b5aa454c093c8.rlib
```

This is as far as I've been able to get so far. I appreciate any help you're able to offer, this looks like a really cool project!

**Comment by agg23** [comment]
Thanks for trying it out. Sorry everything isn't polished nicely; it's been a long process to figure out what building looks like for these systems.

https://github.com/agg23/openfpga-litex/tree/master/lang/rust#building

> As stated above, you need to ensure you have the `/.cargo/config.toml` and `riscv32imafdc-unknown-none-elf.json` files in your workspace directory, and the linker path update code in build.rs.

I think this is at the core of your issue, as you don't mention copying those files over. The Rust target that we're using, `riscv32imafdc-unknown-none-elf`, doesn't exist as a pre-existing target, so we tell LLVM how to represent it with the JSON file.

I believe your linker errors are related to the missing `.cargo/config.toml`, as it's not using the provided linker file, and therefore a bunch of symbols are missing.

Hopefully that fixes the issue. If you have suggestions on how to improve the documentation, please let me know.

**Comment by kcsmnt0** [comment]
No worries, I expected this to take me outside my comfort zone a little! I did have the `.json` file copied over, but I didn't have `.cargo/config.toml`; I have that copied over too now.

Double-checking the files, I noticed I actually had a typo in my `--target` flag (`imafc` instead of `imafdc`). I think that might mean those linker errors are kind of a red herring? If I pass the right target name I get a different error:

```
error: Error loading target specification: Could not find specification for target "riscv32imafdc-unknown-none-elf". Run `rustc --print target-list` for a list of built-in targets
```

`rustup target add riscv32imafdc-unknown-none-elf` gives me this error, which I suppose was the source of my typo:

```
error: toolchain 'nightly-x86_64-unknown-linux-gnu' does not contain component 'rust-std' for target 'riscv32imafdc-unknown-none-elf'; did you mean 'riscv32imafc-unknown-none-elf'?
note: not all platforms have the standard library pre-compiled: https://doc.rust-lang.org/nightly/rustc/platform-support.html
help: consider using `cargo build -Z build-std` instead
```

I tried `cargo build -Z build-std --target riscv32imafdc-unknown-none-elf`, which just gives a similar error:

```
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `/home/kcsmnt0/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc - --crate-name ___ --print=file-names --target riscv32imafdc-unknown-none --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg` (exit status: 1)
  --- stderr
  error: Error loading target specification: Could not find specification for target "riscv32imafdc-unknown-none-elf". Run `rustc --print target-list` for a list of built-in targets
```

I'm guessing this means it's not picking up the `.json` file for some reason. Here's my current project structure in case you can spot something else I've missed:

```
test:
build.rs  .cargo  Cargo.lock  Cargo.toml  .git  .gitmodules  README.md  riscv32imafdc-unknown-none-elf.json  src  vendor

test/.cargo:
config.toml

test/src:
main.rs

test/vendor:
openfpga-litex
```

The documentation seems great so far, but one thing in there did confuse me a bit - the Overview section suggests either `.cargo/config.toml` *or* `build.rs` is necessary depending on the situation, but the Building section suggests that both are necessary.

Thanks for the help! I'm just tinkering around so I'm not in any rush to get this working, but I am pretty interested in hacking on little Pocket programs in Rust. Even with a nonstandard build process, this is a whole lot more approachable to me as a software person than any other way to program the Pocket!

**Comment by mcclure** [comment]
@kcsmnt0 : I may be about to just repeat what agg23 said, but:

As you've identified, the examples are designed to run out of the examples directory, and therefore they expect to find the various Rust support files *relative to* the examples directory. They also implicitly make use of the [.cargo/config.toml](https://github.com/agg23/openfpga-litex/tree/master/.cargo/config.toml) which is in the root of the openfpga-litex repository.

If you are trying to make a standalone project rather than running out of examples, you may find it more helpful to use my standalone example repo as a base. For example, [this branch](https://github.com/mcclure/pocket-riscv-rs/tree/minibreak-agg) contains the same code that is in the openfpga-litex repo as the `minibreak`
 example, but .cargo/config.toml etc are set up to live within the repo and point into a submodule checkout of the openfpga-litex tree. Once you have that project structure down you should be able to adapt it for slint or whatever else.

**Comment by agg23** [comment]
You cannot add the target; as I said, it doesn't exist as an existing Rust target platform. Your `--target` argument needs to be:
```
--target riscv32imafdc-unknown-none-elf.json
```

which explicitly instructs `rustc` to use the JSON target. `/.cargo/config.toml` contains an override for that `target` argument so you don't have to pass it manually (unless you want to).

**Comment by mcclure** [comment]
> the Overview section suggests either `.cargo/config.toml` _or_ `build.rs` is necessary depending on the situation, but the Building section suggests that both are necessary.

At the moment, both are necessary. I have been told we could potentially replace in a later revision some of the `cargo/config.toml` stuff with command-line flags to cargo (IE, something like a more complex makefile), but as far as we know you can't address the config.toml directives in build.rs.

**Comment by kcsmnt0** [comment]
@mcclure Ah thanks, that's super helpful! Your repo builds for me with `cargo build --release`.

I'm still not sure why my original setup wasn't building - with `--target riscv32imafdc-unknown-none-elf.json` it fails to find the `core` crate with the error `` the `riscv32imafdc-unknown-none-elf` target may not be installed ``. I'll try to track down the issue by comparison to the working repo when I get a chance, but I've got something that works to build on top of now.
